### ISSUE TITLE
panic on bad command input

### ISSUE THREAD

**Issue by pcj** [bazelbuild/buildtools#1016]
```
$ buildifier foo ''
```

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/bazelbuild/buildtools/edit.parseCommands(0x4, {0xc0000101c0, 0x2, 0xc00011a460})
	edit/buildozer.go:821 +0x38f
github.com/bazelbuild/buildtools/edit.appendCommands(0xc00010c640, 0xc0000796c0, {0xc0000101c0, 0xc000169798, 0xc000115bd0})
	edit/buildozer.go:1096 +0x4f
github.com/bazelbuild/buildtools/edit.Buildozer(0xc00010c640, {0xc0000101c0, 0x2, 0x2})
	edit/buildozer.go:1208 +0x1a5
main.main()
	buildozer/main.go:122 +0x513
```

**Comment by vladmos** [comment]
There's likely a typo in the example command, the traceback mentions buildozer, not buildifier.
