### ISSUE TITLE
Incompatibility with latest rules_go

### ISSUE THREAD

**Issue by ash2k** [bazelbuild/buildtools#327]
With rules_go commit https://github.com/bazelbuild/rules_go/commit/6627c61f391ec5e104b2f74a70fdab9fb6849821 (latest atm) I'm getting the following error:
```console
ERROR: /private/var/tmp/_bazel_ash2k/f81b510999dc06b6dee1cca0f4c5192e/external/com_github_bazelbuild_buildtools/lang/BUILD.bazel:21:1: in go_library rule @com_github_bazelbuild_buildtools//lang:go_default_library: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel_ash2k/f81b510999dc06b6dee1cca0f4c5192e/external/com_github_bazelbuild_buildtools/lang/BUILD.bazel", line 21
                go_library(name = 'go_default_library')
        File "/private/var/tmp/_bazel_ash2k/f81b510999dc06b6dee1cca0f4c5192e/external/io_bazel_rules_go/go/private/rules/library.bzl", line 33, in _go_library_impl
                fail("importpath must be specified in...")
importpath must be specified in this library or one of its embedded libraries

```

**Comment by pmbethe09** [comment]
Hopefully fixed in 
https://github.com/bazelbuild/buildtools/commit/49a6c199e3fbf5d94534b2771868677d3f9c6de9
