### ISSUE TITLE
Docstrings for rule declarations trigger no-effect lint warning

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/buildtools#471]
With buildifier 0.19.2
```
$ ./node_modules/.bin/buildifier --lint=warn
my_public_api = rule(implementation=_thing)
"""
Documentation for my API
"""
stdin:1: unused-variable: Variable "my_public_api" is unused. Please remove it.
To disable the warning, add '@unused' in a comment. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#unused-variable)
stdin:2: no-effect: Expression result is not used. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#no-effect)
my_public_api = rule(implementation = _thing)
```

The second warning is a false positive because the string literal expression is the idiomatic way to document the rule

**Comment by alexeagle** [comment]
See https://skydoc.bazel.build/docs/writing.html#rule-documentation where this pattern is recommended

**Comment by manekinekko** [comment]
This is also the case in 0.20.0

**Comment by laurentlb** [comment]
cc @c-parsons

Prefer this pattern:

```python
my_public_api = rule(
    implementation=_thing,
    doc = """
Documentation for my API
""",
    )
```

The example should be updated.

**Comment by c-parsons** [comment]
The example is updated -- the given documentation page is for the Deprecated Skydoc tool.
I'll follow up in the new year to remove the deprecated documentation.

The new documentation is here: 
https://skydoc.bazel.build/docs/writing_stardoc.html

**Comment by gregmagolan** [comment]
@c-parsons Thanks. I was able to update the offending lines in rules_nodejs. I think you can close this issue.

**Comment by gregmagolan** [comment]
Correction: it's still a problem with the docstring for a `repository_rule` since `repository_rule` doesn't accept a `doc` attribute

**Comment by gregmagolan** [comment]
Related issue that I just came across is that have a `doc` attribute in a rule such as

```
nodejs_binary = rule(
    implementation = _nodejs_binary_impl,
    doc = """
Runs some JavaScript code in NodeJS.
""",
    attrs = _NODEJS_EXECUTABLE_ATTRS,
    executable = True,
    outputs = _NODEJS_EXECUTABLE_OUTPUTS,
)
```

causes a build failure on Ubuntu 14.04 on BazelCI but no on Ubuntu 16.04 or any of the other platforms. This makes this pattern unusable if you're testing against Ubuntu 14.04.

Haven't searched if its a known bug or not yet so posting here so its recorded.

See https://buildkite.com/bazel/rules-nodejs-nodejs/builds/2225#d23b5e97-4a57-43be-a98b-8107adc5a22a. 

```

ERROR: /workdir/docs/BUILD.bazel:17:1: Couldn't build file docs/docs-skydoc.zip: Generating Skylark doc for docs (9 files) failed (Exit 1) skydoc failed: error executing command
--
  | (cd /home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/184/execroot/build_bazel_rules_nodejs && \
  | exec env - \
  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/swift/usr/bin \
  | bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc '--format=html' '--output_file=bazel-out/k8-fastbuild/bin/docs/docs-skydoc.zip' '--strip_prefix=internal/' --overview '--site_root=/rules_nodejs' internal/common/check_bazel_version.bzl internal/history-server/history_server.bzl internal/http-server/http_server.bzl internal/jasmine_node_test/jasmine_node_test.bzl internal/node/node.bzl internal/node/node_repositories.bzl internal/npm_install/npm_install.bzl internal/npm_package/npm_package.bzl internal/rollup/rollup_bundle.bzl)
  | Execution platform: @bazel_tools//platforms:host_platform
  |  
  | Use --sandbox_debug to see verbose messages from the sandbox: skydoc failed: error executing command
  | (cd /home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/184/execroot/build_bazel_rules_nodejs && \
  | exec env - \
  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/swift/usr/bin \
  | bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc '--format=html' '--output_file=bazel-out/k8-fastbuild/bin/docs/docs-skydoc.zip' '--strip_prefix=internal/' --overview '--site_root=/rules_nodejs' internal/common/check_bazel_version.bzl internal/history-server/history_server.bzl internal/http-server/http_server.bzl internal/jasmine_node_test/jasmine_node_test.bzl internal/node/node.bzl internal/node/node_repositories.bzl internal/npm_install/npm_install.bzl internal/npm_package/npm_package.bzl internal/rollup/rollup_bundle.bzl)
  | Execution platform: @bazel_tools//platforms:host_platform
  |  
  | Use --sandbox_debug to see verbose messages from the sandbox
  | Traceback (most recent call last):
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/184/execroot/build_bazel_rules_nodejs/bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/io_bazel_skydoc/skydoc/main.py", line 334, in <module>
  | main(sys.argv)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/184/execroot/build_bazel_rules_nodejs/bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/io_bazel_skydoc/skydoc/main.py", line 312, in main
  | rule_doc_extractor.parse_bzl(bzl_file, load_symbols)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/184/execroot/build_bazel_rules_nodejs/bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/io_bazel_skydoc/skydoc/rule_extractor.py", line 253, in parse_bzl
  | self._process_skylark(bzl_file, load_symbols)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/184/execroot/build_bazel_rules_nodejs/bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/io_bazel_skydoc/skydoc/rule_extractor.py", line 114, in _process_skylark
  | env = self._exec_code(compiled, global_stubs)
  | File "/home/bazel/.cache/bazel/_bazel_bazel/ec321eb2cc2d0f8f91b676b6d4c66c29/sandbox/linux-sandbox/184/execroot/build_bazel_rules_nodejs/bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/io_bazel_skydoc/skydoc/rule_extractor.py", line 96, in _exec_code
  | exec(compiled, env)
  | File "internal/node/node.bzl", line 343, in <module>
  | doc = "Runs some JavaScript code in NodeJS.",
  | TypeError: rule() got an unexpected keyword argument 'doc'
  | INFO: Elapsed time: 26.031s, Critical Path: 13.81s
  | INFO: 206 processes: 193 remote cache hit, 9 linux-sandbox, 4 local.
  | FAILED: Build did NOT complete successfully
  | bazel build failed with exit code 1
  | 🚨 Error: The command exited with status 1
```

**Comment by c-parsons** [comment]
> Correction: it's still a problem with the docstring for a repository_rule since repository_rule doesn't accept a doc attribute

What version of Bazel are you using? `repository_rule` has a `doc` parameter in the most recent release.

The other error you've cited is because the old, deprecated "Skydoc" tool does not recognize the `doc` parameter. I would recommend you migrate to Stardoc.

**Comment by gregmagolan** [comment]
> What version of Bazel are you using? `repository_rule` has a `doc` parameter in the most recent release.

rules_nodejs was on 0.23.0; just updated to 0.24.1 this morning so will try this again. Thanks
 
> The other error you've cited is because the old, deprecated "Skydoc" tool does not recognize the `doc` parameter. I would recommend you migrate to Stardoc.

Roger
