### ISSUE TITLE
Build fails on Windoows

### ISSUE THREAD

**Issue by xykivo** [bazelbuild/buildtools#663]
When trying to build on Windows (directly from master), there are build errors:

PS C:\Users\dsmolars\Code\buildtools> bazel build //buildifier
INFO: Call stack for the definition of repository 'com_github_golang_protobuf' which is a git_repository (rule definition at C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/bazel_tools/tools/build_defs/repo/git.bzl:252:18):
 - C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/io_bazel_rules_go/go/private/repositories.bzl:237:9
 - C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/io_bazel_rules_go/go/private/repositories.bzl:54:5
 - C:/users/dsmolars/code/buildtools/WORKSPACE:22:1
INFO: Call stack for the definition of repository 'org_golang_x_tools' which is a git_repository (rule definition at C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/bazel_tools/tools/build_defs/repo/git.bzl:252:18):
 - C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/io_bazel_rules_go/go/private/repositories.bzl:237:9
 - C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/io_bazel_rules_go/go/private/repositories.bzl:38:5
 - C:/users/dsmolars/code/buildtools/WORKSPACE:22:1
ERROR: An error occurred during the fetch of repository 'com_github_golang_protobuf':
   Traceback (most recent call last):
        File "C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning com_github_golang_protobuf:
+ cd C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external
+ rm -rf C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/com_github_golang_protobuf C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/com_github_golang_protobuf
/usr/bin/bash: line 5: rm: command not found
INFO: Call stack for the definition of repository 'local_config_cc' which is a cc_autoconf (rule definition at C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/bazel_tools/tools/cpp/cc_configure.bzl:121:15):
 - C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/bazel_tools/tools/cpp/cc_configure.bzl:162:5
 - /DEFAULT.WORKSPACE.SUFFIX:293:1
ERROR: C:/users/dsmolars/code/buildtools/edit/BUILD.bazel:3:1: no such package '@com_github_golang_protobuf//proto': Traceback (most recent call last):
        File "C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning com_github_golang_protobuf:
+ cd C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external
+ rm -rf C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/com_github_golang_protobuf C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/com_github_golang_protobuf
/usr/bin/bash: line 5: rm: command not found
 and referenced by '//edit:go_default_library'
ERROR: Analysis of target '//buildifier:buildifier' failed; build aborted: no such package '@com_github_golang_protobuf//proto': Traceback (most recent call last):
        File "C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 234
                _clone_or_update(ctx)
        File "C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 74, in _clone_or_update
                fail(("error cloning %s:\n%s" % (ctx....)))
error cloning com_github_golang_protobuf:
+ cd C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external
+ rm -rf C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/com_github_golang_protobuf C:/users/dsmolars/_bazel_dsmolars/6t3c6d5b/external/com_github_golang_protobuf
/usr/bin/bash: line 5: rm: command not found
INFO: Elapsed time: 390.518s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (31 packages loaded, 6461 targets configured)
PS C:\Users\dsmolars\Code\buildtools>

**Comment by xykivo** [comment]
I see a similar issue when trying to add a dependency on the buildifier in another project by adding dependencies and buildifer rule directly in the WORKSPACE and root BUILD file.
