### ISSUE TITLE
Unable to build buildifier

### ISSUE THREAD

**Issue by gandhisagar** [bazelbuild/buildtools#708]
FAILED: Build did NOT complete successfully (33 packages loaded, 4292 targets configured)
    Fetching @local_config_cc; fetching
    Fetching @org_golang_x_tools; Cloning 589c23e65e65055d47b9ad4a99723bc389136265 of https://go.googlesource.com/tools
Internal error thrown during build. Printing stack trace: java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.base/java.util.Formatter.format(Unknown Source)
	at java.base/java.util.Formatter.format(Unknown Source)
	at java.base/java.lang.String.format(Unknown Source)
	at com.google.devtools.build.lib.skyframe.SkyframeDependencyResolver.getTargets(SkyframeDependencyResolver.java:145)
	at com.google.devtools.build.lib.analysis.DependencyResolver.dependentNodeMap(DependencyResolver.java:274)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.computeDependencies(ConfiguredTargetFunction.java:562)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:317)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.bubbleErrorUp(AbstractExceptionalParallelEvaluator.java:495)
	at com.google.devtools.build.skyframe.ParallelEvaluator.bubbleErrorUpExceptionally(ParallelEvaluator.java:77)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.waitForCompletionAndConstructResult(AbstractExceptionalParallelEvaluator.java:282)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.doMutatingEvaluation(AbstractExceptionalParallelEvaluator.java:265)
	at com.google.devtools.build.skyframe.AbstractExceptionalParallelEvaluator.evalExceptionally(AbstractExceptionalParallelEvaluator.java:201)
	at com.google.devtools.build.skyframe.ParallelEvaluator.eval(Pa

**Comment by gandhisagar** [comment]
ERROR: An error occurred during the fetch of repository 'org_golang_x_tools':
   Traceback (most recent call last):
	File "/home/sagarg/.cache/bazel/_bazel_sagarg/ba15b5b3410a1f77d3a210ec65d27f2e/external/bazel_tools/tools/build_defs/repo/git.bzl", line 163
		_clone_or_update(ctx)
	File "/home/sagarg/.cache/bazel/_bazel_sagarg/ba15b5b3410a1f77d3a210ec65d27f2e/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/home/sagarg/.cache/bazel/_bazel_sagarg/ba15b5b3410a1f77d3a210ec65d27f2e/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/home/sagarg/.cache/bazel/_bazel_sagarg/ba15b5b3410a1f77d3a210ec65d27f2e/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 103, in _update
		fetch(ctx, git_repo)
	File "/home/sagarg/.cache/bazel/_bazel_sagarg/ba15b5b3410a1f77d3a210ec65d27f2e/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 124, in fetch
		_git_maybe_shallow(ctx, git_repo, "fetch", "--all")
	File "/home/sagarg/.cache/bazel/_bazel_sagarg/ba15b5b3410a1f77d3a210ec65d27f2e/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 159, in _git_maybe_shallow
		_error(ctx.name, (start + args_list), st.st...)
	File "/home/sagarg/.cache/bazel/_bazel_sagarg/ba15b5b3410a1f77d3a210ec65d27f2e/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 169, in _error
		fail(("error running '%s' while worki...)))
error running 'git fetch --all' while working with @org_golang_x_tools:
fatal: unable to access 'https://go.googlesource.com/tools/': error setting certificate verify locations:
  CAfile: /usr/share/ssl/certs/ca-bundle.crt
  CApath: none
error: Could not fetch origin

**Comment by gandhisagar** [comment]
was able to proceed by running 
"git config --global http.sslverify "false""
