### ISSUE TITLE
Error: 'list' value has no field or method '_values' when doing bazel run //:buildifier

### ISSUE THREAD

**Issue by codecakes** [bazelbuild/buildtools#909]
Runnin on ubuntu 18.04 ;
buildifier is added as per instructions in repo in WORKSPACE and

```
load("@com_github_bazelbuild_buildtools//buildifier:def.bzl", "buildifier")

buildifier(
    name = "buildifier",
)
```

Error it spews:

```bash
WARNING: Switched off --watchfs again... temporarily falling back to manually checking files for changes
INFO: Build options --action_env, --build_python_zip, and --copt have changed, discarding analysis cache.
ERROR: /home/info/.cache/bazel/_bazel_info/a8c2fdf963a1b6c21ada954bb5aa49b3/external/io_bazel_rules_go/go/tools/coverdata/BUILD.bazel:3:16: in go_tool_library rule @io_bazel_rules_go//go/tools/coverdata:coverdata: 
Traceback (most recent call last):
        File "/home/info/.cache/bazel/_bazel_info/a8c2fdf963a1b6c21ada954bb5aa49b3/external/io_bazel_rules_go/go/tools/coverdata/BUILD.bazel", line 3, column 16, in go_tool_library(name = 'coverdata')
                go_tool_library(
        File "/home/info/.cache/bazel/_bazel_info/a8c2fdf963a1b6c21ada954bb5aa49b3/external/io_bazel_rules_go/go/private/rules/library.bzl", line 42, column 25, in _go_library_impl
                archive = go.archive(go, source)
        File "/home/info/.cache/bazel/_bazel_info/a8c2fdf963a1b6c21ada954bb5aa49b3/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 218, column 29, in emit_archive
                cgo_exports = sets.union(cgo_exports, *[a.cgo_exports for a in direct])
        File "/home/info/.cache/bazel/_bazel_info/a8c2fdf963a1b6c21ada954bb5aa49b3/external/bazel_skylib/lib/new_sets.bzl", line 190, column 42, in _union
                return struct(_values = dicts.add(*[s._values for s in args]))
Error: 'list' value has no field or method '_values'
INFO: Repository rules_proto instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /home/info/.cache/bazel/_bazel_info/a8c2fdf963a1b6c21ada954bb5aa49b3/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//:buildifier' failed; build aborted: Analysis failed
INFO: Elapsed time: 2.547s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (34 packages loaded, 6488 targets configured)
FAILED: Build did NOT complete successfully (34 packages loaded, 6488 targets configured)
    currently loading: @com_google_protobuf//

```

**Comment by vladmos** [comment]
Probably the versions hardcoded in the README files are out of date. I'll send a PR with the updated versions (and also bump the versions of the deps used by buildtools).
